### ISSUE TITLE
Missing values if using newer mmdvmhost version or dmrhost service

### ISSUE THREAD

**Issue by dl8tu** [on7lds/NextionDriver#14]
I have recognized a strange behavior using different mmdvmhost versions or different DMR host service together with NextionDriver.

Using version 20201031, I don't get the location information (t31.txt). 
Everything is fine if I use an older version 20200924.

Together with this I noticed another issue.
I'm also running [DisplayServer](https://github.com/BrandMeister/DisplayServer) and [DMRHost](https://github.com/BrandMeister/DMRHost) which are based on the MMDVMHost code.
Together with the NextionDriver I don't get the information for loadavg (t22.txt) and Disk free (t23.txt). Using the MMDVMHost service, everything is fine.

As far as I understand, the NextionDriver acts as a service between the host service and the display. So how does the running DMR host service affects the display of the additional values? I had thought that these additional values would be displayed independently of the host service. Am I wrong?

**Comment by on7lds** [comment]
There are a number of things to keep in mind: 

1. the location is sent if the 'XTRA' directive is active. So change
//#define XTRA
in NextionDriver.h to
#define XTRA
and then recompile

2. NextionDriver looks for the date/time field and when this is detected, it sends this field to the display together with these extra data (load, location, ...)
So be sure to enable the clock (**DisplayClock=1** parameter in the Nextion section of the config) 

3. Pay attention: use the latest Displayserver code because the code for the clock was completed only recently. Indeed, 'older' Displayserver versions might lack the clock and thus the load etc will not be displayed

**Comment by dl8tu** [comment]
Hi,

Thank you for your fast response. I'm very sorry but I did not check that I have to comment in the XTRA value.
It's everytime the same, reading the sources could be helpful sometimes ...
 
Thus, this issue can be closed - NextionDriver works as expected also with DisplayServer.

73!
