### ISSUE TITLE
CPU Temp not localized

### ISSUE THREAD

**Issue by rd0fun** [on7lds/NextionDriver#18]
I struggled with this for some time. My Nextion would display degrees C, then update to degree F, then return to C.
I have set rpi localization options for USA. I have set "TempInFarenheit=1" in mmdvmhost on pi-star. Etc.

I could not get this to stay as degrees F !!

Then I looked at basicFunctions.c and I uncommented the temp conversion lines, recompiled, and VOILA!

Would it be possible to change the NextionDriver and the installer so that the locale is identified, and a NextionDriver binary is compiled and installed by the NextionDriverInstaller that respects the localized temp settings?

Thanks!

Others may be just as confused by this as I was. I know a few people that were!  ;-)

**Comment by on7lds** [comment]
The code to handle the temperature which was originally introduced in NextionDriver, was included in MMDVMHost at some point.
I then excluded it from NextionDriver with the possibility to include it by means of a conditional compile (#define XTRA in NextionDriver.h)
Somehow that #define has been uncommented again and therefore NextionDriver also was sending temperatures.

I commented it again, so that should have been solved.
