### ISSUE TITLE
T13-T17 not populating

### ISSUE THREAD

**Issue by VE3RD** [on7lds/NextionDriver#22]
I was running version 1.24 with the filter
SendUserDataMask=0b00001110
DMR Screen would not populate T13-17, with or without the filter
on both 2,4, or 3,5 inch K nextion screens

Reverted back to version 1,20 and all is well

Phil VE3RD

**Comment by KE7FNS** [comment]
`
if (((1<<page)&sendUserDataMask)&&(strstr(TXbuffer,"t0.txt")!=NULL)&&(TXbuffer[8]!='"')) {

if ((2&(1<<page)&sendUserDataMask)&&(strstr(TXbuffer,"t2.txt")!=NULL)&&(TXbuffer[8]!='"')) {
`
There are some serious logic issues with the above code changes.

First off, (2&1<<page) when page == 2, is always false, so it has to be (4&1<<page) to correctly detect page 2,.  That change makes it so that it never tries to search for a callsign in t2.txt because all the other modes don't have a timeslot 2 except the DMR page which is 2.

Second.  The bitmasks are off by one bit shift.

`0b00000001 DStar  
0b00000010 DMR  
0b00000100 YSF  
0b00001000 P25  
0b00010000 NXDN  
0b00100000 POCSAG  
0b01000000 M17  `  

MMDVM is page 0, and (1<<page) when page is 0 is b00000001.
DStar is page 1, and (1<<page) when page is 1 is b00000010, not 0b00000001.
DMR is page 2, and (1<<page) when page is 2 is b00000100, not 0b00000010.
YSF is page 3, and (1<<page) when page is 3 is b00001000, not 0b00000100.
P25 is page 4, and (1<<page) when page is 4 is b00010000, not 0b00001000.
NXDN is page 5, and (1<<page) when page is 5 is b00100000, not 0b00010000.
POCSAG is page 6, and (1<<page) when page is 6 is b01000000, not 0b00100000.
M17 is page 7, and (1<<page) when page is 7 is b10000000, not 0b01000000.

If you kept the wrongly documented bitmasks, you have to subtract the page by 1  (1<<page-1), and that creates another issue when page is 0, because that would be 1 << -1 which is undefined.

Way confusing code.

**Comment by KE7FNS** [comment]
I made the two above changes (4&1<<page) and set SendUserDataMask=0b00000100 for the DMR page.

Tested and t13-t17 were populated on the DMR page correctly.

I'd make a PR but its late and I'm to lazy to upload the code and do all the busywork for just a few line changes.


ON7LSD Don't forget to adjust/shift the default SendUserDataMask too.
https://github.com/on7lds/NextionDriver/blob/de54a3f3c5a736c361babeaf5d849f2de0e3e684/helpers.c#L242

I understand why you did what you did, but dang all that bitshifting and anding stuff gets hell of confusing.

**Comment by VE3RD** [comment]
I am no expert in this code, but I made the suggested changes and got DMR working
However P25 needs a little more work. From the log you can see that it is searching users.csv for a portion of my call, stripping off the VE and of couse I get a not found.  Anyone point me in the the right direction ??

Feb  4 17:22:04 pi-star5 NextionDriver: RX:   t0.txt="N VE3RD"
Feb  4 17:22:04 pi-star5 NextionDriver:  TX:  t0.txt="N VE3RD"
Feb  4 17:22:04 pi-star5 NextionDriver:  NET: t0.txt="N VE3RD"
Feb  4 17:22:04 pi-star5 NextionDriver:   LH: check [t0.txt="N VE3RD"] on page 4
Feb  4 17:22:04 pi-star5 NextionDriver:   LH: page 4 field 0 is [txt="N VE3RD"]
Feb  4 17:22:04 pi-star5 NextionDriver:   LH: statusval 5
Feb  4 17:22:04 pi-star5 NextionDriver: Search for call [3RD]
Feb  4 17:22:04 pi-star5 NextionDriver: --- User index search for call 3RD (0 [] - 212672 [[KC2UOW] )

**Comment by KE7FNS** [comment]
> I am no expert in this code, but I made the suggested changes and got DMR working

Yeah, me either, but I've seen it long enough that I understand what its doing.  I spoke with @on7lds earlier today and he has revised his code and done something different to preserve the bitmasks and documentation he wrote originally.  I tested his new solution and it displayed things correctly for DMR TS2.  I expect he'll push an update in the next day or so when he has free time.

> However P25 needs a little more work. From the log you can see that it is searching users.csv for a portion of my call, stripping off the VE and of couse I get a not found. Anyone point me in the the right direction ??
> 

Yeah, I see exactly what the issue is.

The code looks at position 12 of the string and expects it to contain a callsign.  

for DMR position 12 works.
t0.txt="1 N VE3RD"
t2.txt="2 N VE3RD"

but in all the other modes position 12 is 2 locations too far.  This is because those modes don't insert a 1 or a 2 and a space.
t0.txt="N VE3RD"

So position 12 is the 3, and thats why it snags 3RD.

So the code is going to have to adjust the position 12 or 10 based on if its the DMR page, or the other mode pages.  Now that I think about it the POCSAG page is probably going to need its own index too, I have no idea what is sent for that mode.

**Comment by VE3RD** [comment]
Thank you for the above. 
I changed all the &TXbuffer[12] to &TXbuffer[10] in the pertinent block of code and now all t18-t22 fields fill in with the correct info.

**Comment by KE7FNS** [comment]
> Thank you for the above. I changed all the &TXbuffer[12] to &TXbuffer[10] in the pertinent block of code and now all t18-t22 fields fill in with the correct info.

Yean but it isn't that easy, because now you've broken a lookup back on the DMR page. (unless you don't care about the DMR page at all, then its fine)

It needs to be something similar to this:

if (page==2)
  then TXbuffer[12]
  else TXbuffer[10]

And that assumes that all of the other modes/pages all have the same text output where the callsign begins at position 10 in each one.  I really don't know if thats the case cause I've never poked around with the other modes, only DMR.  I'd have to dig through the MMDVMHost source code to be sure.

I'd just sit and wait for a fix, cause odds are when a fix eventually comes it'll be different than what was discussed.  For example the changes I posted yesterday, @on7lds came up with a completely different solution, so he'll probably think of a different way to handle the different positions of the callsign.  

I'd just wait cause you will just be updating it again when the next commit gets pushed, so why waste the time messing around with it twice.

**Comment by VE3RD** [comment]
There are two completely separate lookup routines. One for DMR page and one for all other modes.

DMR fills in t13-t17. All other modes fill in t18-t22. Can't see anything that is broken so far. P25 and DMR work fine.
Still in test mode for now.

I have a script that will cleanly switch over to the new NextionDriver when ON7LDS posts it.  Depending on what he does, this may need a little tweaking, but bash scripts are my thing.  I am 72years old with nothing to do but play(program) on my computer, so not worried about spending a little time tweaking. Just not good at C language, but can follow the logic trail.

**Comment by KE7FNS** [comment]
> There are two completely separate lookup routines. One for DMR page and one for all other modes.
> 

Yes, there are two lookup routines, but its not one for DMR and the other for all the other modes.

Its one for timeslot 1 and one for timeslot 2.  DMR is the only mode with two timeslots, the rest don't have timeslots.

> DMR fills in t13-t17. All other modes fill in t18-t22. 

Not true.  DMR TS1 uses t18-22.  DMR TS2 uses t13-T17.  

>Can't see anything that is broken so far. P25 and DMR work fine. Still in test mode for now.

Keyup DMR TS2, and you'll see a lookup for your callsign fail cause its looking for "N VE3RD" because position 10 is not the start of your callsign, position 12 is.  Not sure how you claim it works fine for DMR TS1, it should still have the start of callsign position problem.

> 
> I have a script that will cleanly switch over to the new NextionDriver when ON7LDS posts it. Depending on what he does, this may need a little tweaking, but bash scripts are my thing.

So does @on7lds its called NextionDriverInstaller.

**Comment by KE7FNS** [comment]
> Keyup DMR TS2, and you'll see a lookup for your callsign fail cause its looking for "N VE3RD" because position 10 is not the start of your callsign, position 12 is.

Actually after testing it searches for just "N" , so yeah changing the value to 10 breaks things as I had suspected.

```
Feb  5 12:58:37 pi-star NextionDriver: Search for call [N]
Feb  5 12:58:37 pi-star NextionDriver: --- User index search for call N (0 [] - 212736 [[KC2UOW] )
```

**Comment by VE3RD** [comment]
I modified only the section that starts with
    //send user data if found (Slot 1)
    if (((1<<page)&sendUserDataMask)&&(strstr(TXbuffer,"t0.txt")!=NULL)&&(TXbuffer[8]!='"')) {
and changed all references to TXBuffer[12] to TXBuffer[10]. This affect P25, YSF, NXDN etc
Both YSF and P25 work just fine t18-t22

The section for DMR starting with

  //send user data if found (Slot 2)
    if ((4&(1<<page)&sendUserDataMask)&&(strstr(TXbuffer,"t2.txt")!=NULL)&&(TXbuffer[8]!='"')) {
    
was NOT modified and thus the DMR lookup works just fine. t13-t17
NOTE:  if ((4&(1<<page)  was previously  if ((2&(1<<page)     //  DMR Page is 00000100 = 4,  not 2

**Comment by KE7FNS** [comment]
> I modified only the section that starts with //send user data if found (Slot 1) if (((1<<page)&sendUserDataMask)&&(strstr(TXbuffer,"t0.txt")!=NULL)&&(TXbuffer[8]!='"')) { and changed all references to TXBuffer[12] to TXBuffer[10]. This affect P25, YSF, NXDN etc Both YSF and P25 work just fine t18-t22
> 

Yes, and those changes BREAK DMR TS1 lookups, like I said earlier, the fix is not as simple as just mindlessly replacing every occurance of TXbuffer[12] with TXBuffer[10].

Since you are refusing to listen to me explain to you multiple times how it works, simply TEST it with DMR TS1, you'll see your changes now cause searches to fail for DMR TS1.  I tested those same TXbuffer[] changes in both sections with both TS1 and TS2 when I posted the data from the logs earlier.

`
Feb  5 12:58:37 pi-star NextionDriver: Search for call [N]
Feb  5 12:58:37 pi-star NextionDriver: --- User index search for call N (0 [] - 212736 [[KC2UOW] )
`

> The section for DMR starting with
> 
> //send user data if found (Slot 2) if ((4&(1<<page)&sendUserDataMask)&&(strstr(TXbuffer,"t2.txt")!=NULL)&&(TXbuffer[8]!='"')) {
> 
> was NOT modified and thus the DMR lookup works just fine. t13-t17 NOTE: if ((4&(1<<page) was previously if ((2&(1<<page) // DMR Page is 00000100 = 4, not 2

Again, you are wrong, only DMR TS2 lookups work.

DMR TS1 lookups USED  to work before you modified the code to make it work for the other modes.  Thats part of the problem with this new feature that was added, it isn't as simple as just letting the other modes use the same code, cause their string output is different.

**Comment by VE3RD** [comment]
TS1 is Not an option. It does NOT function on a Simplex Hotspot and has no place in our scheme

I am not advocating this mod for general use. It is for me and a small group of users who use simplex hotspots with Nextion 2.4 and 3.5 inch screens, where TS1 is NOT an option. 

T is up to @ON7LDS to revise and publish a version that works for ALL MODES. In the mean time my mod works just fine for DMR TS2, P25 and YSF. When @ON7LDS gets around to making a new version available we will upgrade to it.  Currently, our only option was to revert back to version 1.20. The current version 1,24 is totally unusable.
Best Regards...

**Comment by KE7FNS** [comment]
> TS1 is Not an option. It does NOT function on a Simplex Hotspot and has no place in our scheme
> 
> I am not advocating this mod for general use. It is for me and a small group of users who use simplex hotspots with Nextion 2.4 and 3.5 inch screens, where TS1 is NOT an option.
> 
> T is up to @on7lds to revise and publish a version that works for ALL MODES. In the mean time my mod works just fine for DMR TS2, P25 and YSF. When @on7lds gets around to making a new version available we will upgrade to it. Currently, our only option was to revert back to version 1.20. The current version 1,24 is totally unusable. Best Regards...

Absolutely ridiculous.  Just what the ham world needs another fork of the NextionDriver that only works under certain conditions and myopic limitations of hardware.

**Comment by on7lds** [comment]
correction has been pushed.
I'm in the process of reviewing the data lookup routines to make them find data for as much modes as possible

**Comment by VE3RD** [comment]
Still Not Working for P25
   LH: check [click S0,1] on page 4
Feb  7 12:50:23 pi-star4 NextionDriver: RX:   dim=99
Feb  7 12:50:23 pi-star4 NextionDriver: RX:   t0.txt="N VE3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:  TX:  t0.txt="N VE3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:  NET: t0.txt="N VE3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: check [t0.txt="N VE3RD"] on page 4
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: page 4 field 0 is [txt="N VE3RD"]
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: statusval 5
Feb  7 12:50:23 pi-star4 NextionDriver: LH Inhibit#012
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 212946 [[KC2UOW] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 106473 [KF7EJB] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 53236 [HB9BBM] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 26618 [DK7DN] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 13309 [BG9FMC] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 6654 [AB6XS] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 3327 [5V1JE] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (1663 [2E0WSP] - 3327 [5V1JE] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (1663 [2E0WSP] - 2495 [4G1BID] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2079 [2M0JST] - 2495 [4G1BID] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2287 [2W0RGL] - 2495 [4G1BID] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2287 [2W0RGL] - 2391 [4F1NKS] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2339 [2W1GLY] - 2391 [4F1NKS] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2339 [2W1GLY] - 2365 [4D1Z] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2352 [3B8GW] - 2365 [4D1Z] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2352 [3B8GW] - 2358 [3Z4S] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2352 [3B8GW] - 2355 [3Z1P] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2353 [3DA0MF] - 2355 [3Z1P] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2353 [3DA0MF] - 2354 [3X2021] )
Feb  7 12:50:23 pi-star4 NextionDriver:  TX:  t18.txt="DMRID 3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:  NET: t18.txt="DMRID 3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: check [t18.txt="DMRID 3RD"] on page 4
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: page 4 field 18 is [txt="DMRID 3RD"]
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: statusval 5
Feb  7 12:50:23 pi-star4 NextionDriver: LH Inhibit#012
Feb  7 12:50:23 pi-star4 NextionDriver:  TX:  t19.txt="Not found in"
Feb  7 12:50:24 pi-star4 NextionDriver:  NET: t19.txt="Not found in"

I revised ver 1.24 as follows and had it working  &TXbuffer[12] does not work for non DMR modes
I added a filter on the TS1,P25,YSF etc blocks such that it would ignore DMR all together
and changed all the [&TXbuffer[12] to &TXbuffer[10]

I then duplicated the TS2 block and converted it to TS1

not sure if I broke anything else, but everything I needed was working fine
I
I wrote a script that returns the info string as follows,
/home/pi-star/Scripts/getuserinfo.sh K4WZV
Robert|Springhill|Florida|United States
This functions in all modes, so will be using this until the driver is repaired
